service: apollo-lambda
provider:
  name: aws
  runtime: nodejs14.x
  lambdaHashingVersion: 20201221
  region: us-east-2
package:
  patterns:
  - '!./**'
  - dist/**
  - schema.graphql
  - 'node_modules/**'
functions:
  graphql:
    handler: dist/index.graphqlHandler
    events:
    - http:
        path: /
        method: post
        cors: true
    - http:
        path: /
        method: get
        cors: true
